echo ..............................Change directory...
cd /var/www/app/angular

echo ..............................Install dependencies Package...
npm install

echo ..............................Build project...
npm run build --prod